// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHbvs27pMktYBR-OT06TEVBFV03c72xWs',
    appId: '1:324910213465:web:ff9e114f0775d0e09b8448',
    messagingSenderId: '324910213465',
    projectId: 'marvelpedia-bc95d',
    authDomain: 'marvelpedia-bc95d.firebaseapp.com',
    storageBucket: 'marvelpedia-bc95d.appspot.com',
    measurementId: 'G-5X4ZEWCWFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx53MrtH1H1ut9MrV198pvk90dGupabxo',
    appId: '1:324910213465:android:4fff2328c8e79ea39b8448',
    messagingSenderId: '324910213465',
    projectId: 'marvelpedia-bc95d',
    storageBucket: 'marvelpedia-bc95d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAEbLhFAaKhdUEVfiFJvzoBmxzbBeFuKk',
    appId: '1:324910213465:ios:e36038beb05d7b589b8448',
    messagingSenderId: '324910213465',
    projectId: 'marvelpedia-bc95d',
    storageBucket: 'marvelpedia-bc95d.appspot.com',
    iosBundleId: 'br.dev.coderia.marvelpedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAEbLhFAaKhdUEVfiFJvzoBmxzbBeFuKk',
    appId: '1:324910213465:ios:e36038beb05d7b589b8448',
    messagingSenderId: '324910213465',
    projectId: 'marvelpedia-bc95d',
    storageBucket: 'marvelpedia-bc95d.appspot.com',
    iosBundleId: 'br.dev.coderia.marvelpedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHbvs27pMktYBR-OT06TEVBFV03c72xWs',
    appId: '1:324910213465:web:152f8636fbb171fa9b8448',
    messagingSenderId: '324910213465',
    projectId: 'marvelpedia-bc95d',
    authDomain: 'marvelpedia-bc95d.firebaseapp.com',
    storageBucket: 'marvelpedia-bc95d.appspot.com',
    measurementId: 'G-CN7VQTE16M',
  );
}
